server:
  port: 9092

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : TASK-SERVICE
          uri : lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**
